In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import itertools
import json
import re

import numpy as np
import pandas as pd
import torch
from tqdm import tqdm

from src.analysis import analogy_pseudocausal
from src.analysis.state_space import StateSpaceAnalysisSpec, \
    prepare_state_trajectory, aggregate_state_trajectory, flatten_trajectory
from src.datasets.speech_equivalence import SpeechHiddenStateDataset

In [3]:
base_model = "w2v2_pc_8"

model_class = "ffff_32-pc-mAP1"
model_name = "word_broad_10frames_fixedlen25"

inflection_results_path = "inflection_results.parquet"
all_cross_instances_path = "all_cross_instances.parquet"
false_friends_path = "false_friends.csv"

all_cross_instances_path = "outputs/analogy_morph/inputs/librispeech-train-clean-100/w2v2_pc/all_cross_instances.parquet"
experiments_path = "outputs/analogy_morph/inputs/librispeech-train-clean-100/w2v2_pc/experiments.json"
state_space_specs_path = f"outputs/analogy_morph/inputs/librispeech-train-clean-100/w2v2_pc/state_space_spec.h5"

train_dataset = "librispeech-train-clean-100"
# hidden_states_path = f"outputs/hidden_states/{base_model}/{train_dataset}.h5"
hidden_states_path = f"/scratch/jgauthier/{base_model}_{train_dataset}.h5"

embeddings_path = f"outputs/model_embeddings/{train_dataset}/{base_model}/{model_class}/{model_name}/{train_dataset}.npy"

output_dir = f"."

pos_counts_path = "data/pos_counts.pkl"

seed = 42

metric = "cosine"

agg_fns = [
    ("mean_within_cut", "phoneme")
]

In [4]:
with open(experiments_path, "r") as f:
    experiments = json.load(f)

## Prepare model representations

In [5]:
if embeddings_path == "ID":
    model_representations = SpeechHiddenStateDataset.from_hdf5(hidden_states_path).states
else:
    with open(embeddings_path, "rb") as f:
        model_representations: np.ndarray = np.load(f)
state_space_spec = StateSpaceAnalysisSpec.from_hdf5(state_space_specs_path)
assert state_space_spec.is_compatible_with(model_representations)

/scratch/jgauthier/transformers3/lib/python3.11/site-packages/tables/attributeset.py:322: DataTypeWarning: Unsupported type for attribute 'labels_are_repr' in node '/'. Offending HDF5 class: 8
  value = self._g_getattr(self._v_node, name)

In [6]:
trajectory = prepare_state_trajectory(model_representations, state_space_spec)
trajectory = aggregate_state_trajectory(trajectory, state_space_spec, agg_fns[0])

  0%|          | 0/32046 [00:00<?, ?it/s]

Aggregating:   0%|          | 0/32046 [00:00<?, ?label/s]

In [7]:
agg, agg_src = flatten_trajectory(trajectory)

## Prepare metadata

In [8]:
cuts_df = state_space_spec.cuts.xs("phoneme", level="level").drop(columns=["onset_frame_idx", "offset_frame_idx"])
cuts_df["label_idx"] = cuts_df.index.get_level_values("label").map({l: i for i, l in enumerate(state_space_spec.labels)})
cuts_df["frame_idx"] = cuts_df.groupby(["label", "instance_idx"]).cumcount()
cuts_df = cuts_df.reset_index().set_index(["label", "instance_idx", "frame_idx"]).sort_index()

cut_phonemic_forms = cuts_df.groupby(["label", "instance_idx"]).description.agg(' '.join)

In [9]:
all_cross_instances = pd.read_parquet(all_cross_instances_path).astype({"inflected_instance_idx": int})

In [10]:
all_cross_instances

,base_phones,orig_post_divergence,inflected,inflected_instance_idx,inflected_idx,inflected_phones,post_divergence,inflection,base,base_idx,base_instance_idx,next_phoneme_idx,next_phoneme,base_inflection,counterfactual,next_phoneme_cohort,index
0,AA K Y AH P EY SH AH N,Z,occupational,0,16088,AA K Y AH P EY SH AH N AH L,AH L,NNS-AH,occupation,4463.0,0.0,9,AH,NNS,False,|AH|,NaN
1,AA K Y AH P EY SH AH N,Z,occupational,0,16088,AA K Y AH P EY SH AH N AH L,AH L,NNS-AH,occupation,4463.0,1.0,9,AH,NNS,False,|AH|,NaN
2,AA K Y AH P EY SH AH N,Z,occupational,0,16088,AA K Y AH P EY SH AH N AH L,AH L,NNS-AH,occupation,4463.0,2.0,9,AH,NNS,False,|AH|,NaN
3,AA K Y AH P EY SH AH N,Z,occupational,0,16088,AA K Y AH P EY SH AH N AH L,AH L,NNS-AH,occupation,4463.0,3.0,9,AH,NNS,False,|AH|,NaN
4,AA K Y AH P EY SH AH N,Z,occupational,0,16088,AA K Y AH P EY SH AH N AH L,AH L,NNS-AH,occupation,4463.0,4.0,9,AH,NNS,False,|AH|,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21234538,T,EY T,types,9,11299,T AY P S,AY P S,ate_bound_false,None,NaN,NaN,1,AY,None,False,|AA|AE|AH|AO|AW|AY|EH|ER|EY|IH|IY|OW|OY|R|UH|U...,NaN
21234539,T,EY T,types,10,11299,T AY P S,AY P S,ate_bound_false,None,NaN,NaN,1,AY,None,False,|AA|AE|AH|AO|AW|AY|EH|ER|EY|IH|IY|OW|OY|R|UH|U...,NaN
21234540,T,EY T,types,11,11299,T AY P S,AY P S,ate_bound_false,None,NaN,NaN,1,AY,None,False,|AA|AE|AH|AO|AW|AY|EH|ER|EY|IH|IY|OW|OY|R|UH|U...,NaN
21234541,T,EY T,types,12,11299,T AY P S,AY P S,ate_bound_false,None,NaN,NaN,1,AY,None,False,|AA|AE|AH|AO|AW|AY|EH|ER|EY|IH|IY|OW|OY|R|UH|U...,NaN
21234542,T,EY T,types,13,11299,T AY P S,AY P S,ate_bound_false,None,NaN,NaN,1,AY,None,False,|AA|AE|AH|AO|AW|AY|EH|ER|EY|IH|IY|OW|OY|R|UH|U...,NaN

## Prepare prediction equivalences

In [11]:
# Collect prediction equivalence information. This means, for any given target class
# (e.g. the phoneme "S" at position 0), a marking of all tokens (units within words)
# which are a valid match.
# 
# For the evaluation `matches_next_phoneme`, this means only those tokens which are 
# in onset position and have the identity `S`. For the weaker evaluation `matches_next_phoneme_weak`,
# this means all tokens from any word that has the sound `S` in onset position.
# (Predicting any frame of such a word is equally good under the weak evaluation.)

from collections import defaultdict
infl_phones = set(tuple(inflected_phones.strip().split())
                        for inflected_phones in all_cross_instances.query("counterfactual == False")["inflected_phones"].unique())
all_prediction_equivalences = defaultdict(lambda: {
    # "matches_next_phoneme": set(),
    "matches_next_phoneme_weak": set(),
    # "matches_cohort": set()
})

In [12]:
# Map from label, instance idx to list of matching flat idxs
instance_to_flat_idxs = defaultdict(list)
for flat_idx, (label_idx, instance_idx, unit_idx) in enumerate(agg_src):
    instance_to_flat_idxs[state_space_spec.labels[label_idx], instance_idx].append(flat_idx)

In [13]:
for (next_unit, next_unit_idx), rows in tqdm(all_cross_instances.query("counterfactual == False").groupby(["next_phoneme", "next_phoneme_idx"])):
    match_frames = None
    for inflected_phones in infl_phones:
        if next_unit_idx < len(inflected_phones) and inflected_phones[next_unit_idx] == next_unit:
            if match_frames is None:
                match_frames = set(itertools.chain.from_iterable(
                    instance_to_flat_idxs[row.inflected, row.inflected_instance_idx] for row in rows.itertuples()
                ))

            key = (" ".join(inflected_phones[:next_unit_idx + 1]),)
            all_prediction_equivalences[key]["matches_next_phoneme_weak"] |= \
                match_frames
            # all_prediction_equivalences[" ".join(inflected_phones), next_unit_idx]["matches_next_phoneme"] |= \
            #     set(rows[rows.frame_idx == next_unit_idx].traj_flat_idx)

# for (cohort, next_unit_idx), rows in tqdm(all_cross_instances.head(1000).groupby(["base_phones", "next_phoneme_idx"])):
#     cohort_length = cohort.count(" ") + 1
#     match_frames = None
#     for inflected_phones in infl_phones:
#         if len(inflected_phones) > cohort_length and " ".join(inflected_phones[:cohort_length]) == cohort:
#             if match_frames is None:
#                 match_frames = set(itertools.chain.from_iterable(
#                     instance_to_flat_idxs[row.inflected, row.inflected_instance_idx] for row in rows.itertuples()
#                 ))

#             all_prediction_equivalences[" ".join(inflected_phones), next_unit_idx]["matches_cohort"] |= \
#                 match_frames

100%|██████████| 277/277 [00:22<00:00, 12.46it/s]

In [14]:
def study_equiv(label, next_unit_idx):
    key = (" ".join(label.split()[:next_unit_idx]),)
    sample = all_prediction_equivalences[key]["matches_next_phoneme_weak"]
    sample = np.random.choice(list(sample), size=min(5, len(sample)), replace=False)
    for flat_idx in sample:
        label_idx, instance_idx, unit_idx = agg_src[flat_idx]
        print(cut_phonemic_forms.loc[state_space_spec.labels[label_idx]].loc[instance_idx])

In [15]:
study_equiv("R IY Z AH N", 4)

B OW N AH P AA R T IH S T
K AA M AH N
AH NG K AH L
L AO T AH N Z
S T R AH K

In [16]:
all_prediction_equivalences = {
    key: {k: torch.tensor(list(vs)) for k, vs in equivs.items()}
    for key, equivs in all_prediction_equivalences.items()
}

## Behavioral tests

In [17]:
# experiment = "VBZNNS-src_VBZ_S-tgt_VBZ_Z-AH"
# config = experiments[experiment]
# config["equivalence_keys"] = ["inflected_phones"]
# config["prediction_equivalence_keys"] = ["to_inflected_phones"]
# ret = analogy_pseudocausal.run_experiment_equiv_level(
#     experiment, config, state_space_spec, all_cross_instances,
#     agg, agg_src,
#     cut_phonemic_forms=cut_phonemic_forms,
#     prediction_equivalences=all_prediction_equivalences,
#     num_samples=5,
#     device="cpu",
# )

In [18]:
# ret[["from_base_phones", "from", "from_post_divergence", "to_base_phones", "to", "to_inflected_phones", "matches_next_phoneme_weak_target_label", "matches_next_phoneme_weak_predicted_label", "matches_next_phoneme_weak_predicted_phones", "matches_next_phoneme_weak_target_rank", "matches_next_phoneme_weak_target_phones", "matches_next_phoneme_weak_average_precision"]]

In [19]:
# # post-hoc updates
# for config in experiments.values():
#     config["equivalence_keys"] = ["inflected_phones", "next_phoneme_idx"]
#     config["prediction_equivalence_keys"] = ["to_inflected_phones", "to_next_phoneme_idx"]

In [20]:
dev_expts = {k: v for _, (k, v) in zip(range(5), experiments.items())}

In [22]:
device = "cuda:2" if torch.cuda.is_available() else "cpu"
t_agg = torch.tensor(agg, device=device)
t_agg_src = torch.tensor(agg_src, device=device)

# pre-compute flat idx lookup
flat_idx_lookup = {(label_idx, instance_idx, phoneme_idx): flat_idx
                    for flat_idx, (label_idx, instance_idx, phoneme_idx) in enumerate(agg_src)}

experiment_results = pd.concat({
    experiment: analogy_pseudocausal.run_experiment_equiv_level(
        experiment, config,
        state_space_spec, all_cross_instances,
        t_agg, t_agg_src,
        flat_idx_lookup=flat_idx_lookup,
        cut_phonemic_forms=cut_phonemic_forms,
        prediction_equivalences=all_prediction_equivalences,
        num_samples=50,
        max_num_vector_samples=100,
        seed=seed,
        device=device)
    for experiment, config in tqdm(experiments.items(), unit="experiment")
}, names=["experiment"])
# experiment_results["correct"] = experiment_results.predicted_label == experiment_results.gt_label
experiment_results

  0%|          | 0/470 [00:00<?, ?experiment/s]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 1/470 [00:04<35:13,  4.51s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_S-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 2/470 [00:08<35:00,  4.49s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  1%|          | 3/470 [00:13<34:50,  4.48s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  1%|          | 4/470 [00:17<34:47,  4.48s/experiment]

VBZNNS-src_VBZ_S-tgt_VBZ_Z-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  1%|          | 5/470 [00:22<34:28,  4.45s/experiment]

VBZNNS-src_VBZ_S-tgt_VBZ_S-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  1%|▏         | 6/470 [00:27<35:33,  4.60s/experiment]

VBZNNS-src_VBZ_S-tgt_NNS_Z-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  1%|▏         | 7/470 [00:31<35:25,  4.59s/experiment]

VBZNNS-src_VBZ_S-tgt_NNS_S-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  2%|▏         | 8/470 [00:36<35:49,  4.65s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  2%|▏         | 9/470 [00:40<34:58,  4.55s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_S-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  2%|▏         | 10/470 [00:45<35:42,  4.66s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  2%|▏         | 11/470 [00:50<35:13,  4.60s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  3%|▎         | 12/470 [00:54<34:45,  4.55s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  3%|▎         | 13/470 [00:59<34:15,  4.50s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_S-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  3%|▎         | 14/470 [01:03<34:49,  4.58s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  3%|▎         | 15/470 [01:08<34:54,  4.60s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  3%|▎         | 16/470 [01:13<35:22,  4.68s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  4%|▎         | 17/470 [01:17<33:50,  4.48s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  4%|▍         | 18/470 [01:21<33:31,  4.45s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  4%|▍         | 19/470 [01:26<33:19,  4.43s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  4%|▍         | 20/470 [01:30<33:00,  4.40s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  4%|▍         | 21/470 [01:34<33:05,  4.42s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  5%|▍         | 22/470 [01:39<33:32,  4.49s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  5%|▍         | 23/470 [01:43<33:05,  4.44s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  5%|▌         | 24/470 [01:48<33:28,  4.50s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  5%|▌         | 25/470 [01:53<33:53,  4.57s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  6%|▌         | 26/470 [01:57<33:48,  4.57s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_S-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  6%|▌         | 27/470 [02:02<33:36,  4.55s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  6%|▌         | 28/470 [02:06<33:18,  4.52s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  6%|▌         | 29/470 [02:11<33:19,  4.53s/experiment]

VBZNNS-src_VBZ_S-tgt_VBZ_Z-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  6%|▋         | 30/470 [02:15<33:13,  4.53s/experiment]

VBZNNS-src_VBZ_S-tgt_VBZ_S-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  7%|▋         | 31/470 [02:20<33:52,  4.63s/experiment]

VBZNNS-src_VBZ_S-tgt_NNS_Z-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  7%|▋         | 32/470 [02:25<33:58,  4.65s/experiment]

VBZNNS-src_VBZ_S-tgt_NNS_S-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  7%|▋         | 33/470 [02:30<34:18,  4.71s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  7%|▋         | 34/470 [02:34<33:32,  4.62s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_S-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  7%|▋         | 35/470 [02:39<33:29,  4.62s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  8%|▊         | 36/470 [02:44<33:29,  4.63s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  8%|▊         | 37/470 [02:48<33:12,  4.60s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  8%|▊         | 38/470 [02:53<33:00,  4.58s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_S-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  8%|▊         | 39/470 [02:57<33:20,  4.64s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  9%|▊         | 40/470 [03:02<33:21,  4.65s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  9%|▊         | 41/470 [03:07<34:06,  4.77s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  9%|▉         | 42/470 [03:11<32:23,  4.54s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_S-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  9%|▉         | 43/470 [03:16<32:30,  4.57s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  9%|▉         | 44/470 [03:20<31:11,  4.39s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 10%|▉         | 45/470 [03:25<32:26,  4.58s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 10%|▉         | 46/470 [03:29<31:37,  4.48s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_S-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 10%|█         | 47/470 [03:34<31:51,  4.52s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 10%|█         | 48/470 [03:38<31:15,  4.44s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 10%|█         | 49/470 [03:42<31:12,  4.45s/experiment]

VBZNNS-src_VBZ_S-tgt_VBZ_Z-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 11%|█         | 50/470 [03:47<31:24,  4.49s/experiment]

VBZNNS-src_VBZ_S-tgt_VBZ_S-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 11%|█         | 51/470 [03:52<31:48,  4.56s/experiment]

VBZNNS-src_VBZ_S-tgt_NNS_Z-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 11%|█         | 52/470 [03:56<31:46,  4.56s/experiment]

VBZNNS-src_VBZ_S-tgt_NNS_S-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 11%|█▏        | 53/470 [04:01<32:34,  4.69s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 11%|█▏        | 54/470 [04:06<31:48,  4.59s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_S-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 12%|█▏        | 55/470 [04:10<31:52,  4.61s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 12%|█▏        | 56/470 [04:15<32:03,  4.65s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 12%|█▏        | 57/470 [04:20<31:55,  4.64s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 12%|█▏        | 58/470 [04:24<31:44,  4.62s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_S-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 13%|█▎        | 59/470 [04:29<31:59,  4.67s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 13%|█▎        | 60/470 [04:34<32:02,  4.69s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 13%|█▎        | 61/470 [04:39<32:27,  4.76s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 13%|█▎        | 62/470 [04:43<31:31,  4.64s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 13%|█▎        | 63/470 [04:47<30:54,  4.56s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 14%|█▎        | 64/470 [04:52<30:57,  4.57s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 14%|█▍        | 65/470 [04:56<30:32,  4.52s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 14%|█▍        | 66/470 [05:01<29:54,  4.44s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 14%|█▍        | 67/470 [05:05<30:03,  4.48s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 14%|█▍        | 68/470 [05:09<29:41,  4.43s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_S-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 15%|█▍        | 69/470 [05:14<29:58,  4.48s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 15%|█▍        | 70/470 [05:18<29:49,  4.47s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 15%|█▌        | 71/470 [05:23<29:51,  4.49s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 15%|█▌        | 72/470 [05:28<30:06,  4.54s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_S-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 16%|█▌        | 73/470 [05:32<30:34,  4.62s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 16%|█▌        | 74/470 [05:37<30:29,  4.62s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 16%|█▌        | 75/470 [05:42<31:01,  4.71s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 16%|█▌        | 76/470 [05:46<30:07,  4.59s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 16%|█▋        | 77/470 [05:51<29:41,  4.53s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 17%|█▋        | 78/470 [05:55<29:44,  4.55s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 17%|█▋        | 79/470 [06:00<29:18,  4.50s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 17%|█▋        | 80/470 [06:04<29:05,  4.47s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 17%|█▋        | 81/470 [06:09<29:46,  4.59s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 17%|█▋        | 82/470 [06:14<29:55,  4.63s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 18%|█▊        | 83/470 [06:18<29:44,  4.61s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 18%|█▊        | 84/470 [06:23<29:44,  4.62s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 18%|█▊        | 85/470 [06:27<29:00,  4.52s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 18%|█▊        | 86/470 [06:31<27:49,  4.35s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 19%|█▊        | 87/470 [06:36<27:51,  4.36s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 19%|█▊        | 88/470 [06:40<27:15,  4.28s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 19%|█▉        | 89/470 [06:44<27:23,  4.31s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 19%|█▉        | 90/470 [06:48<27:30,  4.34s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 19%|█▉        | 91/470 [06:53<27:21,  4.33s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 20%|█▉        | 92/470 [06:57<27:34,  4.38s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 20%|█▉        | 93/470 [07:02<27:52,  4.44s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 20%|██        | 94/470 [07:06<27:40,  4.42s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 20%|██        | 95/470 [07:11<28:29,  4.56s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 20%|██        | 96/470 [07:16<29:08,  4.67s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 21%|██        | 97/470 [07:20<28:26,  4.57s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_S-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 21%|██        | 98/470 [07:25<28:15,  4.56s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 21%|██        | 99/470 [07:29<27:37,  4.47s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 21%|██▏       | 100/470 [07:34<27:38,  4.48s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 21%|██▏       | 101/470 [07:38<27:40,  4.50s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 22%|██▏       | 102/470 [07:43<28:09,  4.59s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 22%|██▏       | 103/470 [07:48<28:37,  4.68s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 22%|██▏       | 104/470 [07:53<28:49,  4.73s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 22%|██▏       | 105/470 [07:58<29:13,  4.80s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 23%|██▎       | 106/470 [08:03<29:28,  4.86s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 23%|██▎       | 107/470 [08:07<28:24,  4.69s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 23%|██▎       | 108/470 [08:12<28:09,  4.67s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 23%|██▎       | 109/470 [08:16<27:31,  4.58s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 23%|██▎       | 110/470 [08:20<27:22,  4.56s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-G

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 24%|██▎       | 111/470 [08:25<26:33,  4.44s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_S-G

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 24%|██▍       | 112/470 [08:29<26:41,  4.47s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-G

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 24%|██▍       | 113/470 [08:34<26:47,  4.50s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-G

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 24%|██▍       | 114/470 [08:38<26:47,  4.52s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 24%|██▍       | 115/470 [08:43<26:23,  4.46s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 25%|██▍       | 116/470 [08:47<26:51,  4.55s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 25%|██▍       | 117/470 [08:52<26:46,  4.55s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 25%|██▌       | 118/470 [08:56<26:16,  4.48s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 25%|██▌       | 119/470 [09:01<26:40,  4.56s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 26%|██▌       | 120/470 [09:06<27:05,  4.64s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 26%|██▌       | 121/470 [09:11<27:08,  4.67s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 26%|██▌       | 122/470 [09:16<27:56,  4.82s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 26%|██▌       | 123/470 [09:21<28:15,  4.89s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 26%|██▋       | 124/470 [09:25<27:21,  4.74s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 27%|██▋       | 125/470 [09:30<26:58,  4.69s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 27%|██▋       | 126/470 [09:35<28:32,  4.98s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 27%|██▋       | 127/470 [09:40<28:19,  4.95s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 27%|██▋       | 128/470 [09:45<27:22,  4.80s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 27%|██▋       | 129/470 [09:49<26:50,  4.72s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 28%|██▊       | 130/470 [09:54<26:20,  4.65s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 28%|██▊       | 131/470 [09:58<25:58,  4.60s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 28%|██▊       | 132/470 [10:03<25:43,  4.57s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 28%|██▊       | 133/470 [10:07<25:43,  4.58s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 29%|██▊       | 134/470 [10:12<25:11,  4.50s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 29%|██▊       | 135/470 [10:15<23:54,  4.28s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 29%|██▉       | 136/470 [10:20<24:00,  4.31s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 29%|██▉       | 137/470 [10:24<24:03,  4.33s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 29%|██▉       | 138/470 [10:28<23:45,  4.29s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 30%|██▉       | 139/470 [10:33<23:56,  4.34s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 30%|██▉       | 140/470 [10:37<24:03,  4.37s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-JH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 30%|███       | 141/470 [10:41<23:31,  4.29s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-JH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 30%|███       | 142/470 [10:46<23:54,  4.37s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 30%|███       | 143/470 [10:50<23:32,  4.32s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 31%|███       | 144/470 [10:55<23:40,  4.36s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 31%|███       | 145/470 [10:59<23:53,  4.41s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 31%|███       | 146/470 [11:04<23:51,  4.42s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 31%|███▏      | 147/470 [11:08<24:05,  4.48s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 31%|███▏      | 148/470 [11:13<24:28,  4.56s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 32%|███▏      | 149/470 [11:18<24:54,  4.66s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 32%|███▏      | 150/470 [11:23<24:52,  4.67s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 32%|███▏      | 151/470 [11:27<24:44,  4.65s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 32%|███▏      | 152/470 [11:32<24:26,  4.61s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 33%|███▎      | 153/470 [11:36<24:34,  4.65s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 33%|███▎      | 154/470 [11:41<24:54,  4.73s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-TH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 33%|███▎      | 155/470 [11:45<23:48,  4.54s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-TH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 33%|███▎      | 156/470 [11:50<23:21,  4.46s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-Y

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 33%|███▎      | 157/470 [11:54<23:06,  4.43s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-Y

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 34%|███▎      | 158/470 [11:59<23:13,  4.47s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 34%|███▍      | 159/470 [12:03<22:51,  4.41s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 34%|███▍      | 160/470 [12:07<22:57,  4.44s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 34%|███▍      | 161/470 [12:11<22:21,  4.34s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 34%|███▍      | 162/470 [12:17<23:22,  4.55s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 35%|███▍      | 163/470 [12:21<22:51,  4.47s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_S-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 35%|███▍      | 164/470 [12:25<23:05,  4.53s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 35%|███▌      | 165/470 [12:30<23:08,  4.55s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 35%|███▌      | 166/470 [12:35<23:01,  4.54s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 36%|███▌      | 167/470 [12:39<22:42,  4.50s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_S-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 36%|███▌      | 168/470 [12:44<23:38,  4.70s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 36%|███▌      | 169/470 [12:49<23:33,  4.70s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 36%|███▌      | 170/470 [12:54<23:39,  4.73s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-HH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 36%|███▋      | 171/470 [12:58<22:38,  4.54s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-HH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 37%|███▋      | 172/470 [13:02<22:18,  4.49s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-HH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 37%|███▋      | 173/470 [13:07<22:23,  4.52s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 37%|███▋      | 174/470 [13:11<21:49,  4.42s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 37%|███▋      | 175/470 [13:15<21:41,  4.41s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_S-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 37%|███▋      | 176/470 [13:20<21:48,  4.45s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 38%|███▊      | 177/470 [13:24<21:49,  4.47s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 38%|███▊      | 178/470 [13:29<22:10,  4.56s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_S-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 38%|███▊      | 179/470 [13:34<22:19,  4.60s/experiment]

VBZNNS-src_NNS_S-tgt_VBZ_Z-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 38%|███▊      | 180/470 [13:38<22:09,  4.58s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_Z-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 39%|███▊      | 181/470 [13:43<22:36,  4.69s/experiment]

VBZNNS-src_NNS_S-tgt_NNS_S-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 39%|███▊      | 182/470 [13:48<22:51,  4.76s/experiment]

VBZNNS-src_VBZ_Z-tgt_VBZ_Z-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 39%|███▉      | 183/470 [13:52<21:15,  4.44s/experiment]

VBZNNS-src_VBZ_Z-tgt_NNS_Z-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 39%|███▉      | 184/470 [13:56<20:51,  4.38s/experiment]

VBZNNS-src_NNS_Z-tgt_VBZ_Z-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 39%|███▉      | 185/470 [14:00<20:27,  4.31s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 40%|███▉      | 186/470 [14:05<20:28,  4.33s/experiment]

VBZNNS-src_NNS_Z-tgt_NNS_Z-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 40%|███▉      | 187/470 [14:09<20:24,  4.33s/experiment]

ly-src_True-tgt_True-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 40%|████      | 188/470 [14:12<17:59,  3.83s/experiment]

ly-src_True-tgt_False-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 40%|████      | 189/470 [14:14<16:01,  3.42s/experiment]

ly-src_False-tgt_True-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 40%|████      | 190/470 [14:16<14:26,  3.10s/experiment]

ly-src_False-tgt_False-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 41%|████      | 191/470 [14:19<13:27,  2.89s/experiment]

ion-src_True-tgt_True-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 41%|████      | 192/470 [14:21<12:26,  2.68s/experiment]

ion-src_True-tgt_False-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 41%|████      | 193/470 [14:23<11:47,  2.55s/experiment]

ion-src_False-tgt_True-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 41%|████▏     | 194/470 [14:26<11:13,  2.44s/experiment]

ion-src_False-tgt_False-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 41%|████▏     | 195/470 [14:28<10:47,  2.36s/experiment]

ate-src_False-tgt_True-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 42%|████▏     | 196/470 [14:30<10:48,  2.37s/experiment]

ate-src_False-tgt_False-K

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 42%|████▏     | 197/470 [14:33<11:05,  2.44s/experiment]

ly-src_True-tgt_True-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 42%|████▏     | 198/470 [14:35<11:19,  2.50s/experiment]

ly-src_True-tgt_False-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 42%|████▏     | 199/470 [14:38<11:10,  2.48s/experiment]

ly-src_False-tgt_True-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 43%|████▎     | 200/470 [14:40<11:22,  2.53s/experiment]

ly-src_False-tgt_False-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 43%|████▎     | 201/470 [14:43<11:21,  2.53s/experiment]

ion-src_True-tgt_True-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 43%|████▎     | 202/470 [14:45<10:53,  2.44s/experiment]

ion-src_True-tgt_False-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 43%|████▎     | 203/470 [14:47<10:39,  2.40s/experiment]

ion-src_False-tgt_True-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 43%|████▎     | 204/470 [14:50<10:37,  2.39s/experiment]

ion-src_False-tgt_False-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 44%|████▎     | 205/470 [14:52<10:43,  2.43s/experiment]

ate-src_True-tgt_False-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 44%|████▍     | 206/470 [14:55<11:02,  2.51s/experiment]

ate-src_False-tgt_False-T

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 44%|████▍     | 207/470 [14:58<11:04,  2.53s/experiment]

ly-src_False-tgt_False-UH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 44%|████▍     | 208/470 [15:00<11:05,  2.54s/experiment]

ate-src_True-tgt_True-UH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 44%|████▍     | 209/470 [15:03<11:57,  2.75s/experiment]

ate-src_True-tgt_False-UH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 45%|████▍     | 210/470 [15:06<11:52,  2.74s/experiment]

ate-src_False-tgt_True-UH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 45%|████▍     | 211/470 [15:09<11:40,  2.70s/experiment]

ate-src_False-tgt_False-UH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 45%|████▌     | 212/470 [15:12<11:51,  2.76s/experiment]

ate-src_True-tgt_True-OY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 45%|████▌     | 213/470 [15:14<11:29,  2.68s/experiment]

ate-src_True-tgt_False-OY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 46%|████▌     | 214/470 [15:17<11:07,  2.61s/experiment]

ate-src_False-tgt_True-OY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 46%|████▌     | 215/470 [15:19<10:46,  2.54s/experiment]

ate-src_False-tgt_False-OY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 46%|████▌     | 216/470 [15:21<10:40,  2.52s/experiment]

ly-src_True-tgt_True-DH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 46%|████▌     | 217/470 [15:24<10:38,  2.52s/experiment]

ly-src_True-tgt_False-DH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 46%|████▋     | 218/470 [15:26<10:32,  2.51s/experiment]

ly-src_False-tgt_True-DH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 47%|████▋     | 219/470 [15:29<10:53,  2.60s/experiment]

ly-src_False-tgt_False-DH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 47%|████▋     | 220/470 [15:32<11:09,  2.68s/experiment]

ly-src_True-tgt_True-HH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 47%|████▋     | 221/470 [15:34<10:41,  2.58s/experiment]

ly-src_True-tgt_False-HH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 47%|████▋     | 222/470 [15:37<10:27,  2.53s/experiment]

ly-src_True-tgt_True-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 47%|████▋     | 223/470 [15:39<10:23,  2.52s/experiment]

ly-src_True-tgt_False-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 48%|████▊     | 224/470 [15:42<10:18,  2.51s/experiment]

ly-src_False-tgt_True-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 48%|████▊     | 225/470 [15:44<10:16,  2.52s/experiment]

ly-src_False-tgt_False-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 48%|████▊     | 226/470 [15:47<10:09,  2.50s/experiment]

ion-src_True-tgt_True-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 48%|████▊     | 227/470 [15:49<09:49,  2.43s/experiment]

ion-src_True-tgt_False-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 49%|████▊     | 228/470 [15:51<09:34,  2.37s/experiment]

ion-src_False-tgt_True-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 49%|████▊     | 229/470 [15:54<09:31,  2.37s/experiment]

ion-src_False-tgt_False-S

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 49%|████▉     | 230/470 [15:56<09:40,  2.42s/experiment]

ly-src_True-tgt_True-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 49%|████▉     | 231/470 [15:59<09:38,  2.42s/experiment]

ly-src_True-tgt_False-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 49%|████▉     | 232/470 [16:01<09:37,  2.43s/experiment]

ly-src_False-tgt_True-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 50%|████▉     | 233/470 [16:04<09:43,  2.46s/experiment]

ly-src_False-tgt_False-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 50%|████▉     | 234/470 [16:06<09:38,  2.45s/experiment]

ate-src_True-tgt_True-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 50%|█████     | 235/470 [16:09<10:00,  2.56s/experiment]

ate-src_True-tgt_False-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 50%|█████     | 236/470 [16:12<10:09,  2.60s/experiment]

ate-src_False-tgt_True-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 50%|█████     | 237/470 [16:14<10:20,  2.66s/experiment]

ate-src_False-tgt_False-EH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 51%|█████     | 238/470 [16:17<10:42,  2.77s/experiment]

ly-src_True-tgt_True-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 51%|█████     | 239/470 [16:20<10:14,  2.66s/experiment]

ly-src_True-tgt_False-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 51%|█████     | 240/470 [16:22<09:52,  2.58s/experiment]

ly-src_False-tgt_True-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 51%|█████▏    | 241/470 [16:25<09:36,  2.52s/experiment]

ly-src_False-tgt_False-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 51%|█████▏    | 242/470 [16:27<09:36,  2.53s/experiment]

ion-src_True-tgt_True-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 52%|█████▏    | 243/470 [16:30<09:28,  2.50s/experiment]

ion-src_True-tgt_False-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 52%|█████▏    | 244/470 [16:32<09:18,  2.47s/experiment]

ion-src_False-tgt_True-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 52%|█████▏    | 245/470 [16:34<09:06,  2.43s/experiment]

ion-src_False-tgt_False-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 52%|█████▏    | 246/470 [16:37<08:59,  2.41s/experiment]

ate-src_False-tgt_True-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 53%|█████▎    | 247/470 [16:39<09:00,  2.42s/experiment]

ate-src_False-tgt_False-P

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 53%|█████▎    | 248/470 [16:42<09:00,  2.43s/experiment]

ly-src_True-tgt_True-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 53%|█████▎    | 249/470 [16:44<08:49,  2.40s/experiment]

ly-src_True-tgt_False-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 53%|█████▎    | 250/470 [16:47<09:06,  2.49s/experiment]

ly-src_False-tgt_True-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 53%|█████▎    | 251/470 [16:49<09:00,  2.47s/experiment]

ly-src_False-tgt_False-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 54%|█████▎    | 252/470 [16:51<08:51,  2.44s/experiment]

ion-src_True-tgt_True-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 54%|█████▍    | 253/470 [16:54<08:40,  2.40s/experiment]

ion-src_True-tgt_False-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 54%|█████▍    | 254/470 [16:56<08:34,  2.38s/experiment]

ion-src_False-tgt_True-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 54%|█████▍    | 255/470 [16:58<08:29,  2.37s/experiment]

ion-src_False-tgt_False-F

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 54%|█████▍    | 256/470 [17:01<08:26,  2.37s/experiment]

ly-src_True-tgt_True-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 55%|█████▍    | 257/470 [17:03<08:39,  2.44s/experiment]

ly-src_True-tgt_False-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 55%|█████▍    | 258/470 [17:06<08:31,  2.41s/experiment]

ly-src_False-tgt_True-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 55%|█████▌    | 259/470 [17:08<08:37,  2.45s/experiment]

ly-src_False-tgt_False-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 55%|█████▌    | 260/470 [17:11<08:26,  2.41s/experiment]

ion-src_True-tgt_True-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 56%|█████▌    | 261/470 [17:13<08:18,  2.38s/experiment]

ion-src_True-tgt_False-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 56%|█████▌    | 262/470 [17:15<08:18,  2.40s/experiment]

ion-src_False-tgt_True-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 56%|█████▌    | 263/470 [17:18<08:02,  2.33s/experiment]

ion-src_False-tgt_False-V

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 56%|█████▌    | 264/470 [17:20<07:59,  2.33s/experiment]

ly-src_True-tgt_True-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 56%|█████▋    | 265/470 [17:22<08:04,  2.36s/experiment]

ly-src_True-tgt_False-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 57%|█████▋    | 266/470 [17:25<08:01,  2.36s/experiment]

ly-src_False-tgt_True-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 57%|█████▋    | 267/470 [17:27<07:55,  2.34s/experiment]

ly-src_False-tgt_False-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 57%|█████▋    | 268/470 [17:29<07:59,  2.37s/experiment]

ion-src_True-tgt_True-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 57%|█████▋    | 269/470 [17:32<07:55,  2.36s/experiment]

ion-src_True-tgt_False-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 57%|█████▋    | 270/470 [17:34<07:52,  2.36s/experiment]

ion-src_False-tgt_True-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 58%|█████▊    | 271/470 [17:36<07:34,  2.28s/experiment]

ion-src_False-tgt_False-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 58%|█████▊    | 272/470 [17:39<07:35,  2.30s/experiment]

ate-src_True-tgt_True-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 58%|█████▊    | 273/470 [17:41<07:49,  2.38s/experiment]

ate-src_True-tgt_False-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 58%|█████▊    | 274/470 [17:44<08:11,  2.51s/experiment]

ate-src_False-tgt_True-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 59%|█████▊    | 275/470 [17:47<08:29,  2.62s/experiment]

ate-src_False-tgt_False-AH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 59%|█████▊    | 276/470 [17:50<09:07,  2.82s/experiment]

ly-src_True-tgt_True-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 59%|█████▉    | 277/470 [17:52<08:36,  2.68s/experiment]

ly-src_True-tgt_False-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 59%|█████▉    | 278/470 [17:55<08:14,  2.57s/experiment]

ly-src_False-tgt_True-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 59%|█████▉    | 279/470 [17:57<08:09,  2.56s/experiment]

ly-src_False-tgt_False-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 60%|█████▉    | 280/470 [18:00<08:07,  2.57s/experiment]

ate-src_True-tgt_True-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 60%|█████▉    | 281/470 [18:03<08:14,  2.62s/experiment]

ate-src_True-tgt_False-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 60%|██████    | 282/470 [18:06<08:39,  2.76s/experiment]

ate-src_False-tgt_True-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 60%|██████    | 283/470 [18:08<08:34,  2.75s/experiment]

ate-src_False-tgt_False-ER

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 60%|██████    | 284/470 [18:12<08:56,  2.88s/experiment]

ly-src_True-tgt_True-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 61%|██████    | 285/470 [18:14<08:38,  2.80s/experiment]

ly-src_True-tgt_False-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 61%|██████    | 286/470 [18:17<08:21,  2.73s/experiment]

ly-src_False-tgt_True-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 61%|██████    | 287/470 [18:19<08:04,  2.65s/experiment]

ly-src_False-tgt_False-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 61%|██████▏   | 288/470 [18:22<07:46,  2.56s/experiment]

ion-src_True-tgt_True-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 61%|██████▏   | 289/470 [18:24<07:43,  2.56s/experiment]

ion-src_True-tgt_False-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 62%|██████▏   | 290/470 [18:26<07:23,  2.47s/experiment]

ion-src_False-tgt_True-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 62%|██████▏   | 291/470 [18:29<07:22,  2.47s/experiment]

ion-src_False-tgt_False-SH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 62%|██████▏   | 292/470 [18:31<07:15,  2.44s/experiment]

ly-src_True-tgt_True-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 62%|██████▏   | 293/470 [18:34<07:21,  2.49s/experiment]

ly-src_True-tgt_False-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 63%|██████▎   | 294/470 [18:36<07:18,  2.49s/experiment]

ly-src_False-tgt_True-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 63%|██████▎   | 295/470 [18:39<07:29,  2.57s/experiment]

ly-src_False-tgt_False-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 63%|██████▎   | 296/470 [18:42<07:35,  2.62s/experiment]

ate-src_True-tgt_True-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 63%|██████▎   | 297/470 [18:44<07:34,  2.62s/experiment]

ate-src_True-tgt_False-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 63%|██████▎   | 298/470 [18:47<07:36,  2.65s/experiment]

ate-src_False-tgt_True-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 64%|██████▎   | 299/470 [18:50<07:42,  2.70s/experiment]

ate-src_False-tgt_False-IY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 64%|██████▍   | 300/470 [18:53<08:10,  2.88s/experiment]

ly-src_True-tgt_True-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 64%|██████▍   | 301/470 [18:56<07:48,  2.77s/experiment]

ly-src_True-tgt_False-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 64%|██████▍   | 302/470 [18:59<07:44,  2.77s/experiment]

ly-src_False-tgt_True-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 64%|██████▍   | 303/470 [19:01<07:22,  2.65s/experiment]

ly-src_False-tgt_False-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 65%|██████▍   | 304/470 [19:03<07:04,  2.56s/experiment]

ion-src_True-tgt_True-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 65%|██████▍   | 305/470 [19:06<06:47,  2.47s/experiment]

ion-src_True-tgt_False-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 65%|██████▌   | 306/470 [19:08<06:40,  2.44s/experiment]

ion-src_False-tgt_True-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 65%|██████▌   | 307/470 [19:10<06:36,  2.43s/experiment]

ion-src_False-tgt_False-Z

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 66%|██████▌   | 308/470 [19:13<06:40,  2.47s/experiment]

ly-src_True-tgt_True-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 66%|██████▌   | 309/470 [19:15<06:32,  2.44s/experiment]

ly-src_True-tgt_False-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 66%|██████▌   | 310/470 [19:18<06:32,  2.45s/experiment]

ly-src_False-tgt_True-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 66%|██████▌   | 311/470 [19:20<06:24,  2.42s/experiment]

ly-src_False-tgt_False-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 66%|██████▋   | 312/470 [19:22<06:15,  2.38s/experiment]

ion-src_True-tgt_True-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 67%|██████▋   | 313/470 [19:25<06:11,  2.37s/experiment]

ion-src_True-tgt_False-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 67%|██████▋   | 314/470 [19:27<06:08,  2.36s/experiment]

ion-src_False-tgt_True-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 67%|██████▋   | 315/470 [19:29<06:02,  2.34s/experiment]

ion-src_False-tgt_False-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 67%|██████▋   | 316/470 [19:32<05:58,  2.33s/experiment]

ate-src_False-tgt_True-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 67%|██████▋   | 317/470 [19:34<06:07,  2.40s/experiment]

ate-src_False-tgt_False-M

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 68%|██████▊   | 318/470 [19:37<06:19,  2.50s/experiment]

ly-src_False-tgt_True-AW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 68%|██████▊   | 319/470 [19:39<06:14,  2.48s/experiment]

ly-src_False-tgt_False-AW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 68%|██████▊   | 320/470 [19:42<06:17,  2.52s/experiment]

ate-src_True-tgt_True-AW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 68%|██████▊   | 321/470 [19:44<06:14,  2.51s/experiment]

ate-src_True-tgt_False-AW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 69%|██████▊   | 322/470 [19:48<06:39,  2.70s/experiment]

ate-src_False-tgt_True-AW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 69%|██████▊   | 323/470 [19:51<06:44,  2.75s/experiment]

ate-src_False-tgt_False-AW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 69%|██████▉   | 324/470 [19:53<06:37,  2.72s/experiment]

ly-src_True-tgt_True-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 69%|██████▉   | 325/470 [19:56<06:21,  2.63s/experiment]

ly-src_True-tgt_False-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 69%|██████▉   | 326/470 [19:58<06:13,  2.59s/experiment]

ly-src_False-tgt_True-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 70%|██████▉   | 327/470 [20:01<06:07,  2.57s/experiment]

ly-src_False-tgt_False-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 70%|██████▉   | 328/470 [20:03<06:08,  2.59s/experiment]

ion-src_False-tgt_False-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 70%|███████   | 329/470 [20:06<06:04,  2.59s/experiment]

ate-src_True-tgt_True-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 70%|███████   | 330/470 [20:09<06:16,  2.69s/experiment]

ate-src_True-tgt_False-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 70%|███████   | 331/470 [20:12<06:37,  2.86s/experiment]

ate-src_False-tgt_True-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 71%|███████   | 332/470 [20:15<06:36,  2.88s/experiment]

ate-src_False-tgt_False-IH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 71%|███████   | 333/470 [20:19<07:08,  3.13s/experiment]

ly-src_False-tgt_True-Y

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 71%|███████   | 334/470 [20:21<06:48,  3.00s/experiment]

ly-src_False-tgt_False-Y

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 71%|███████▏  | 335/470 [20:24<06:28,  2.87s/experiment]

ate-src_True-tgt_True-Y

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 71%|███████▏  | 336/470 [20:26<06:12,  2.78s/experiment]

ate-src_True-tgt_False-Y

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 72%|███████▏  | 337/470 [20:29<05:52,  2.65s/experiment]

ate-src_False-tgt_True-Y

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 72%|███████▏  | 338/470 [20:32<05:55,  2.70s/experiment]

ate-src_False-tgt_False-Y

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 72%|███████▏  | 339/470 [20:34<05:45,  2.63s/experiment]

ly-src_True-tgt_True-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 72%|███████▏  | 340/470 [20:37<05:35,  2.58s/experiment]

ly-src_True-tgt_False-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 73%|███████▎  | 341/470 [20:40<05:50,  2.72s/experiment]

ly-src_False-tgt_True-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 73%|███████▎  | 342/470 [20:42<05:45,  2.70s/experiment]

ly-src_False-tgt_False-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 73%|███████▎  | 343/470 [20:45<05:48,  2.74s/experiment]

ion-src_True-tgt_True-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 73%|███████▎  | 344/470 [20:47<05:25,  2.58s/experiment]

ion-src_True-tgt_False-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 73%|███████▎  | 345/470 [20:50<05:13,  2.51s/experiment]

ion-src_False-tgt_True-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 74%|███████▎  | 346/470 [20:52<05:07,  2.48s/experiment]

ion-src_False-tgt_False-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 74%|███████▍  | 347/470 [20:55<05:03,  2.47s/experiment]

ate-src_True-tgt_True-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 74%|███████▍  | 348/470 [20:57<05:00,  2.47s/experiment]

ate-src_True-tgt_False-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 74%|███████▍  | 349/470 [20:59<04:59,  2.48s/experiment]

ate-src_False-tgt_True-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 74%|███████▍  | 350/470 [21:02<05:08,  2.57s/experiment]

ate-src_False-tgt_False-L

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 75%|███████▍  | 351/470 [21:05<05:07,  2.58s/experiment]

ly-src_True-tgt_True-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 75%|███████▍  | 352/470 [21:07<05:01,  2.55s/experiment]

ly-src_True-tgt_False-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 75%|███████▌  | 353/470 [21:10<05:02,  2.59s/experiment]

ly-src_False-tgt_True-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 75%|███████▌  | 354/470 [21:12<04:52,  2.52s/experiment]

ly-src_False-tgt_False-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 76%|███████▌  | 355/470 [21:15<04:41,  2.44s/experiment]

ion-src_True-tgt_True-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 76%|███████▌  | 356/470 [21:17<04:35,  2.42s/experiment]

ion-src_True-tgt_False-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 76%|███████▌  | 357/470 [21:19<04:30,  2.39s/experiment]

ion-src_False-tgt_True-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 76%|███████▌  | 358/470 [21:22<04:34,  2.45s/experiment]

ion-src_False-tgt_False-CH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 76%|███████▋  | 359/470 [21:25<04:38,  2.51s/experiment]

ly-src_True-tgt_True-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 77%|███████▋  | 360/470 [21:27<04:29,  2.45s/experiment]

ly-src_True-tgt_False-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 77%|███████▋  | 361/470 [21:29<04:26,  2.44s/experiment]

ly-src_False-tgt_True-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 77%|███████▋  | 362/470 [21:32<04:22,  2.43s/experiment]

ly-src_False-tgt_False-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 77%|███████▋  | 363/470 [21:34<04:23,  2.46s/experiment]

ate-src_True-tgt_True-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 77%|███████▋  | 364/470 [21:37<04:25,  2.51s/experiment]

ate-src_True-tgt_False-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 78%|███████▊  | 365/470 [21:40<04:45,  2.72s/experiment]

ate-src_False-tgt_True-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 78%|███████▊  | 366/470 [21:43<04:48,  2.77s/experiment]

ate-src_False-tgt_False-OW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 78%|███████▊  | 367/470 [21:46<04:50,  2.82s/experiment]

ly-src_True-tgt_True-JH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 78%|███████▊  | 368/470 [21:48<04:36,  2.71s/experiment]

ly-src_True-tgt_False-JH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 79%|███████▊  | 369/470 [21:51<04:22,  2.60s/experiment]

ly-src_False-tgt_True-JH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 79%|███████▊  | 370/470 [21:53<04:11,  2.52s/experiment]

ly-src_False-tgt_False-JH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 79%|███████▉  | 371/470 [21:55<04:03,  2.46s/experiment]

ly-src_False-tgt_True-UW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 79%|███████▉  | 372/470 [21:58<04:00,  2.45s/experiment]

ly-src_False-tgt_False-UW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 79%|███████▉  | 373/470 [22:00<04:03,  2.51s/experiment]

ate-src_True-tgt_True-UW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 80%|███████▉  | 374/470 [22:03<04:05,  2.56s/experiment]

ate-src_True-tgt_False-UW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 80%|███████▉  | 375/470 [22:06<04:05,  2.59s/experiment]

ate-src_False-tgt_True-UW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 80%|████████  | 376/470 [22:09<04:08,  2.65s/experiment]

ate-src_False-tgt_False-UW

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 80%|████████  | 377/470 [22:12<04:26,  2.86s/experiment]

ly-src_True-tgt_True-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 80%|████████  | 378/470 [22:14<04:07,  2.69s/experiment]

ly-src_True-tgt_False-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 81%|████████  | 379/470 [22:17<03:54,  2.58s/experiment]

ly-src_False-tgt_True-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 81%|████████  | 380/470 [22:19<03:44,  2.50s/experiment]

ly-src_False-tgt_False-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 81%|████████  | 381/470 [22:21<03:41,  2.49s/experiment]

ion-src_True-tgt_True-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 81%|████████▏ | 382/470 [22:24<03:34,  2.43s/experiment]

ion-src_True-tgt_False-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 81%|████████▏ | 383/470 [22:26<03:26,  2.38s/experiment]

ion-src_False-tgt_True-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 82%|████████▏ | 384/470 [22:28<03:21,  2.35s/experiment]

ion-src_False-tgt_False-B

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 82%|████████▏ | 385/470 [22:30<03:18,  2.34s/experiment]

ly-src_False-tgt_True-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 82%|████████▏ | 386/470 [22:33<03:19,  2.38s/experiment]

ly-src_False-tgt_False-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 82%|████████▏ | 387/470 [22:35<03:22,  2.43s/experiment]

ate-src_True-tgt_True-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 83%|████████▎ | 388/470 [22:38<03:25,  2.51s/experiment]

ate-src_True-tgt_False-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 83%|████████▎ | 389/470 [22:41<03:35,  2.66s/experiment]

ate-src_False-tgt_True-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 83%|████████▎ | 390/470 [22:44<03:29,  2.62s/experiment]

ate-src_False-tgt_False-AA

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 83%|████████▎ | 391/470 [22:47<03:42,  2.82s/experiment]

ly-src_True-tgt_True-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 83%|████████▎ | 392/470 [22:50<03:33,  2.74s/experiment]

ly-src_True-tgt_False-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 84%|████████▎ | 393/470 [22:52<03:25,  2.67s/experiment]

ly-src_False-tgt_True-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 84%|████████▍ | 394/470 [22:55<03:19,  2.63s/experiment]

ly-src_False-tgt_False-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 84%|████████▍ | 395/470 [22:57<03:18,  2.65s/experiment]

ate-src_True-tgt_True-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 84%|████████▍ | 396/470 [23:00<03:16,  2.66s/experiment]

ate-src_True-tgt_False-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 84%|████████▍ | 397/470 [23:03<03:15,  2.68s/experiment]

ate-src_False-tgt_True-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 85%|████████▍ | 398/470 [23:05<03:15,  2.71s/experiment]

ate-src_False-tgt_False-EY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 85%|████████▍ | 399/470 [23:09<03:21,  2.84s/experiment]

ly-src_True-tgt_True-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 85%|████████▌ | 400/470 [23:11<03:13,  2.77s/experiment]

ly-src_True-tgt_False-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 85%|████████▌ | 401/470 [23:14<03:06,  2.70s/experiment]

ly-src_False-tgt_True-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 86%|████████▌ | 402/470 [23:16<03:01,  2.67s/experiment]

ly-src_False-tgt_False-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 86%|████████▌ | 403/470 [23:19<02:55,  2.62s/experiment]

ion-src_True-tgt_True-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 86%|████████▌ | 404/470 [23:21<02:48,  2.55s/experiment]

ion-src_True-tgt_False-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 86%|████████▌ | 405/470 [23:24<02:41,  2.49s/experiment]

ion-src_False-tgt_True-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 86%|████████▋ | 406/470 [23:26<02:37,  2.46s/experiment]

ion-src_False-tgt_False-D

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 87%|████████▋ | 407/470 [23:28<02:35,  2.47s/experiment]

ly-src_True-tgt_True-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 87%|████████▋ | 408/470 [23:31<02:30,  2.43s/experiment]

ly-src_True-tgt_False-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 87%|████████▋ | 409/470 [23:33<02:29,  2.44s/experiment]

ly-src_False-tgt_True-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 87%|████████▋ | 410/470 [23:36<02:29,  2.49s/experiment]

ly-src_False-tgt_False-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 87%|████████▋ | 411/470 [23:38<02:28,  2.52s/experiment]

ion-src_True-tgt_True-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 88%|████████▊ | 412/470 [23:41<02:22,  2.46s/experiment]

ion-src_True-tgt_False-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 88%|████████▊ | 413/470 [23:43<02:17,  2.41s/experiment]

ion-src_False-tgt_True-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 88%|████████▊ | 414/470 [23:45<02:13,  2.39s/experiment]

ion-src_False-tgt_False-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 88%|████████▊ | 415/470 [23:48<02:13,  2.42s/experiment]

ate-src_True-tgt_True-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 89%|████████▊ | 416/470 [23:51<02:15,  2.51s/experiment]

ate-src_True-tgt_False-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 89%|████████▊ | 417/470 [23:53<02:13,  2.53s/experiment]

ate-src_False-tgt_True-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 89%|████████▉ | 418/470 [23:56<02:13,  2.57s/experiment]

ate-src_False-tgt_False-R

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 89%|████████▉ | 419/470 [23:59<02:15,  2.66s/experiment]

ly-src_True-tgt_True-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 89%|████████▉ | 420/470 [24:01<02:06,  2.53s/experiment]

ly-src_True-tgt_False-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 90%|████████▉ | 421/470 [24:03<02:02,  2.50s/experiment]

ate-src_False-tgt_True-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 90%|████████▉ | 422/470 [24:06<01:57,  2.44s/experiment]

ate-src_False-tgt_False-W

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 90%|█████████ | 423/470 [24:08<01:57,  2.50s/experiment]

ly-src_True-tgt_True-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 90%|█████████ | 424/470 [24:11<01:53,  2.47s/experiment]

ly-src_True-tgt_False-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 90%|█████████ | 425/470 [24:13<01:51,  2.49s/experiment]

ly-src_False-tgt_True-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 91%|█████████ | 426/470 [24:16<01:49,  2.48s/experiment]

ly-src_False-tgt_False-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 91%|█████████ | 427/470 [24:18<01:49,  2.55s/experiment]

ate-src_True-tgt_True-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 91%|█████████ | 428/470 [24:21<01:47,  2.57s/experiment]

ate-src_True-tgt_False-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 91%|█████████▏| 429/470 [24:24<01:53,  2.76s/experiment]

ate-src_False-tgt_True-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 91%|█████████▏| 430/470 [24:27<01:49,  2.75s/experiment]

ate-src_False-tgt_False-AE

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 92%|█████████▏| 431/470 [24:31<01:56,  2.98s/experiment]

ly-src_False-tgt_True-AO

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 92%|█████████▏| 432/470 [24:33<01:50,  2.92s/experiment]

ly-src_False-tgt_False-AO

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 92%|█████████▏| 433/470 [24:36<01:44,  2.83s/experiment]

ate-src_True-tgt_True-AO

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 92%|█████████▏| 434/470 [24:39<01:41,  2.82s/experiment]

ate-src_True-tgt_False-AO

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 93%|█████████▎| 435/470 [24:42<01:38,  2.80s/experiment]

ate-src_False-tgt_True-AO

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 93%|█████████▎| 436/470 [24:44<01:36,  2.85s/experiment]

ate-src_False-tgt_False-AO

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 93%|█████████▎| 437/470 [24:47<01:35,  2.90s/experiment]

ly-src_True-tgt_True-TH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 93%|█████████▎| 438/470 [24:50<01:26,  2.72s/experiment]

ly-src_True-tgt_False-TH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 93%|█████████▎| 439/470 [24:52<01:21,  2.62s/experiment]

ly-src_False-tgt_True-TH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 94%|█████████▎| 440/470 [24:54<01:15,  2.51s/experiment]

ly-src_False-tgt_False-TH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 94%|█████████▍| 441/470 [24:57<01:10,  2.44s/experiment]

ion-src_False-tgt_True-TH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 94%|█████████▍| 442/470 [24:59<01:07,  2.40s/experiment]

ion-src_False-tgt_False-TH

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 94%|█████████▍| 443/470 [25:01<01:05,  2.42s/experiment]

ly-src_True-tgt_True-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 94%|█████████▍| 444/470 [25:04<01:02,  2.41s/experiment]

ly-src_True-tgt_False-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 95%|█████████▍| 445/470 [25:06<00:59,  2.40s/experiment]

ly-src_False-tgt_True-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 95%|█████████▍| 446/470 [25:09<00:57,  2.38s/experiment]

ly-src_False-tgt_False-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 95%|█████████▌| 447/470 [25:11<00:54,  2.38s/experiment]

ion-src_True-tgt_True-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 95%|█████████▌| 448/470 [25:13<00:51,  2.35s/experiment]

ion-src_True-tgt_False-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 96%|█████████▌| 449/470 [25:16<00:50,  2.39s/experiment]

ion-src_False-tgt_True-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 96%|█████████▌| 450/470 [25:18<00:47,  2.37s/experiment]

ion-src_False-tgt_False-NG

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 96%|█████████▌| 451/470 [25:20<00:45,  2.39s/experiment]

ly-src_True-tgt_True-G

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 96%|█████████▌| 452/470 [25:23<00:43,  2.39s/experiment]

ly-src_True-tgt_False-G

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 96%|█████████▋| 453/470 [25:25<00:40,  2.37s/experiment]

ly-src_False-tgt_True-G

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 97%|█████████▋| 454/470 [25:28<00:38,  2.43s/experiment]

ly-src_False-tgt_False-G

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 97%|█████████▋| 455/470 [25:30<00:36,  2.43s/experiment]

ly-src_False-tgt_True-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 97%|█████████▋| 456/470 [25:32<00:33,  2.37s/experiment]

ly-src_False-tgt_False-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 97%|█████████▋| 457/470 [25:35<00:31,  2.42s/experiment]

ate-src_True-tgt_True-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 97%|█████████▋| 458/470 [25:38<00:29,  2.46s/experiment]

ate-src_True-tgt_False-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 98%|█████████▊| 459/470 [25:41<00:30,  2.74s/experiment]

ate-src_False-tgt_True-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 98%|█████████▊| 460/470 [25:44<00:26,  2.70s/experiment]

ate-src_False-tgt_False-AY

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 98%|█████████▊| 461/470 [25:46<00:24,  2.75s/experiment]

ly-src_True-tgt_True-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 98%|█████████▊| 462/470 [25:49<00:21,  2.65s/experiment]

ly-src_True-tgt_False-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 99%|█████████▊| 463/470 [25:51<00:17,  2.56s/experiment]

ly-src_False-tgt_True-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 99%|█████████▊| 464/470 [25:54<00:15,  2.57s/experiment]

ly-src_False-tgt_False-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 99%|█████████▉| 465/470 [25:56<00:12,  2.55s/experiment]

ion-src_True-tgt_True-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 99%|█████████▉| 466/470 [25:59<00:09,  2.48s/experiment]

ion-src_True-tgt_False-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

 99%|█████████▉| 467/470 [26:01<00:07,  2.48s/experiment]

ion-src_False-tgt_True-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

100%|█████████▉| 468/470 [26:03<00:04,  2.41s/experiment]

ion-src_False-tgt_False-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

100%|█████████▉| 469/470 [26:06<00:02,  2.43s/experiment]

ate-src_False-tgt_False-N

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

100%|██████████| 470/470 [26:08<00:00,  3.34s/experiment]

                                  matches_next_phoneme_weak_target_rank  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                       4
                              1                                     547
                              2                                    2876
                              3                                    2460
                              4                                      85
...                                                                 ...
ate-src_False-tgt_False-N     45                                      1
                              46                                      4
                              47                                      1
                              48                                      0
                              49                                      8

                                  matches_next_phoneme_weak_target_distance  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                    0.197780
                              1                                    0.332257
                              2                                    0.502819
                              3                                    0.360834
                              4                                    0.290739
...                                                                     ...
ate-src_False-tgt_False-N     45                                   0.327660
                              46                                   0.160533
                              47                                   0.251233
                              48                                   0.130438
                              49                                   0.192777

                                  matches_next_phoneme_weak_target_label_idx  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                         3032
                              1                                         5900
                              2                                        12379
                              3                                          672
                              4                                        10654
...                                                                      ...
ate-src_False-tgt_False-N     45                                         117
                              46                                         180
                              47                                       16139
                              48                                         180
                              49                                       15944

                                  matches_next_phoneme_weak_target_instance_idx  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                               2
                              1                                              44
                              2                                               2
                              3                                              50
                              4                                               2
...                                                                         ...
ate-src_False-tgt_False-N     45                                             48
                              46                                             29
                              47                                             14
                              48                                             18
                              49                                              1

                                  matches_next_phoneme_weak_target_phoneme_idx  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                              2
                              1                                              0
                              2                                              2
                              3                                              0
                              4                                              2
...                                                                        ...
ate-src_False-tgt_False-N     45                                             1
                              46                                             1
                              47                                             1
                              48                                             1
                              49                                             1

                                 matches_next_phoneme_weak_target_label  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                servants
                              1                                   dutch
                              2                                    bulk
                              3                                   month
                              4                               allowance
...                                                                 ...
ate-src_False-tgt_False-N     45                                   snow
                              46                                  snake
                              47                                   snap
                              48                                  snake
                              49                                   snub

                                 matches_next_phoneme_weak_target_phones  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                          S ER V AH N T S
                              1                                  D AH CH
                              2                                 B AH L K
                              3                                M AH N TH
                              4                           AH L AW AH N S
...                                                                  ...
ate-src_False-tgt_False-N     45                                  S N OW
                              46                                S N EY K
                              47                                S N AE P
                              48                                S N EY K
                              49                                S N AH B

                                  matches_next_phoneme_weak_predicted_distance  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                       0.171980
                              1                                       0.200775
                              2                                       0.280937
                              3                                       0.125816
                              4                                       0.222451
...                                                                        ...
ate-src_False-tgt_False-N     45                                      0.308932
                              46                                      0.146418
                              47                                      0.247735
                              48                                      0.130438
                              49                                      0.176943

                                  matches_next_phoneme_weak_predicted_label_idx  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                            4190
                              1                                            1618
                              2                                           21031
                              3                                           26533
                              4                                            7405
...                                                                         ...
ate-src_False-tgt_False-N     45                                            101
                              46                                          16622
                              47                                          20790
                              48                                            180
                              49                                           1430

                                  matches_next_phoneme_weak_predicted_instance_idx  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                                                  1
                              1                                                 13
                              2                                                  3
                              3                                                  0
                              4                                                  6
...                                                                            ...
ate-src_False-tgt_False-N     45                                                 7
                              46                                                 1
                              47                                                 1
                              48                                                18
                              49                                                92

                                  ...      from_inflected_phones  \
experiment                        ...
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0   ...   T EH L AH G R AE F IH NG
                              1   ...                  OW N AH S
                              2   ...            S ER V AH N T S
                              3   ...  K AH N T IH N Y UW AH N S
                              4   ...           T EH L AH F OW N
...                               ...                        ...
ate-src_False-tgt_False-N     45  ...                   S N EY K
                              46  ...                   S N OW Z
                              47  ...                     S N OW
                              48  ...                   S N OW Z
                              49  ...                   S N AY P

                                    from_base_phones from_post_divergence  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0               T EH L    AH G R AE F IH NG
                              1                 OW N                 AH S
                              2               S ER V             AH N T S
                              3   K AH N T IH N Y UW               AH N S
                              4               T EH L            AH F OW N
...                                              ...                  ...
ate-src_False-tgt_False-N     45                   S               N EY K
                              46                   S               N OW Z
                              47                   S                 N OW
                              48                   S               N OW Z
                              49                   S               N AY P

                                  to_inflected_phones to_base_phones  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0             S ER V AH         S ER V
                              1                 OW AH             OW
                              2                 OW AH             OW
                              3                 OW AH             OW
                              4            AH L AW AH        AH L AW
...                                               ...            ...
ate-src_False-tgt_False-N     45                  S N              S
                              46                  S N              S
                              47                  S N              S
                              48                  S N              S
                              49                  S N              S

                                 to_post_divergence  inflection_from  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0                  AH           VBZ-AH
                              1                  AH           VBZ-AH
                              2                  AH           VBZ-AH
                              3                  AH           VBZ-AH
                              4                  AH           VBZ-AH
...                                             ...              ...
ate-src_False-tgt_False-N     45                  N  ate_bound_false
                              46                  N  ate_bound_false
                              47                  N  ate_bound_false
                              48                  N  ate_bound_false
                              49                  N  ate_bound_false

                                          inflection_to  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0              VBZ-ctf-AH
                              1              VBZ-ctf-AH
                              2              VBZ-ctf-AH
                              3              VBZ-ctf-AH
                              4              VBZ-ctf-AH
...                                                 ...
ate-src_False-tgt_False-N     45  ate_bound_false-ctf-N
                              46  ate_bound_false-ctf-N
                              47  ate_bound_false-ctf-N
                              48  ate_bound_false-ctf-N
                              49  ate_bound_false-ctf-N

                                                          from_equiv_label  \
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0   (T EH L AH G R AE F IH NG, telegraphing)
                              1                          (OW N AH S, onus)
                              2                (S ER V AH N T S, servants)
                              3   (K AH N T IH N Y UW AH N S, continuance)
                              4              (T EH L AH F OW N, telephone)
...                                                                    ...
ate-src_False-tgt_False-N     45                         (S N EY K, snake)
                              46                         (S N OW Z, snows)
                              47                            (S N OW, snow)
                              48                         (S N OW Z, snows)
                              49                         (S N AY P, snipe)

                                          to_equiv_label
experiment
VBZNNS-src_VBZ_Z-tgt_VBZ_Z-AH 0   (S ER V AH, surveying)
                              1       (OW AH, overlooks)
                              2             (OW AH, ode)
                              3         (OW AH, oakdale)
                              4   (AH L AW AH, allowing)
...                                                  ...
ate-src_False-tgt_False-N     45            (S N, spies)
                              46            (S N, sieur)
                              47            (S N, spied)
                              48            (S N, scull)
                              49            (S N, cells)

[23500 rows x 27 columns]

### Save

In [23]:
output_dir = "analogy_pseudocausal_morph"
from pathlib import Path
Path(output_dir).mkdir(parents=True, exist_ok=True)

In [24]:
experiment_results.to_csv(f"{output_dir}/experiment_results.csv")

In [25]:
5

5